### ISSUE TITLE
cheeby downloading duplicate images

### ISSUE THREAD

**Issue by nickqw** [4pr0n/ripme#146]
Occurs on most cheeby albums. The same pictures get ripped over and over and over. Doesn't seem to occur every single time I run a ripper on the albums but probably 1 in every 6 times.

A few examples
http://cheeby.com/u/6wildcat9
http://cheeby.com/u/isagw/pics
http://cheeby.com/u/thediggitydank/pics
http://www.cheeby.com/u/girlthatswallows

**Comment by 4pr0n** [comment]
Fixed in https://github.com/4pr0n/ripme/issues/153

**Comment by nickqw** [comment]
I can still reproduce this. Just updated to 1.0.92 and ripped http://www.cheeby.com/u/deviantrose/pics. This happens pretty frequently where it will just re-rip all of the photos even if they already exist.

I did a fresh rip of this user by deleting the whole folder and re-ripping. I then ripped and it has re-downloaded every photo. The actual filenames of the original and the duplicate are pretty much the same so I can see 063_N3JttJ.jpg as the original but the duplicate of this image now comes up as 105_N3JttJ.jpg. There was also 090_YCDo4L.jpg the original and then a duplicate 132_YCDo4L.jpg. This only occurs on the cheeby ripper for me.

**Comment by 4pr0n** [comment]
Ok. I think I know what the problem is.

Do you have `preserve order` checked in the configuration?

`preserve order` adds a number before every file (`001_`, `002_`, etc). If the order on the site changes (like a new picture is added), all of the numbers become off-by-one.

Or CheebyRipper could be updated to ignore the `preserve order` setting, but that would put all pictures in a random order.

It'd be cool if it stored files like `cheeby_username/album_id/001_image.jpg`
If so, this means whenever a new pictures is added to /u/deviantrose/pics, the program will

**Comment by nickqw** [comment]
Yeah, preserve order is enabled in my settings.

**Comment by 4pr0n** [comment]
v1.1.0 has the changes
